In [30]:
"""
First lets get the common libraries here in play
"""
import pandas as pd
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from scipy.spatial.distance import pdist, squareform

In [31]:
data = pd.read_csv('./data/MTA_Subway_Stations_20241127.csv')

data.head()

GTFS Stop ID  Station ID  Complex ID Division     Line  \
0          R01           1           1      BMT  Astoria   
1          R03           2           2      BMT  Astoria   
2          R04           3           3      BMT  Astoria   
3          R05           4           4      BMT  Astoria   
4          R06           5           5      BMT  Astoria   

              Stop Name Borough    CBD Daytime Routes Structure  \
0  Astoria-Ditmars Blvd       Q  False            N W  Elevated   
1          Astoria Blvd       Q  False            N W  Elevated   
2                 30 Av       Q  False            N W  Elevated   
3              Broadway       Q  False            N W  Elevated   
4                 36 Av       Q  False            N W  Elevated   

   GTFS Latitude  GTFS Longitude North Direction Label South Direction Label  \
0      40.775036      -73.912034             Last Stop             Manhattan   
1      40.770258      -73.917843               Astoria             Manhattan   
2      40.766779      -73.921479               Astoria             Manhattan   
3      40.761820      -73.925508               Astoria             Manhattan   
4      40.756804      -73.929575               Astoria             Manhattan   

   ADA  ADA Northbound  ADA Southbound ADA Notes                  Georeference  
0    0               0               0       NaN  POINT (-73.912034 40.775036)  
1    1               1               1       NaN  POINT (-73.917843 40.770258)  
2    0               0               0       NaN  POINT (-73.921479 40.766779)  
3    0               0               0       NaN   POINT (-73.925508 40.76182)  
4    0               0               0       NaN  POINT (-73.929575 40.756804)

In [32]:
data = data.drop(columns=['CBD', 
                          'Structure', 
                          'ADA', 
                          'ADA Northbound', 
                          'ADA Southbound', 
                          'ADA Notes'])

In [33]:
data.head()

GTFS Stop ID  Station ID  Complex ID Division     Line  \
0          R01           1           1      BMT  Astoria   
1          R03           2           2      BMT  Astoria   
2          R04           3           3      BMT  Astoria   
3          R05           4           4      BMT  Astoria   
4          R06           5           5      BMT  Astoria   

              Stop Name Borough Daytime Routes  GTFS Latitude  GTFS Longitude  \
0  Astoria-Ditmars Blvd       Q            N W      40.775036      -73.912034   
1          Astoria Blvd       Q            N W      40.770258      -73.917843   
2                 30 Av       Q            N W      40.766779      -73.921479   
3              Broadway       Q            N W      40.761820      -73.925508   
4                 36 Av       Q            N W      40.756804      -73.929575   

  North Direction Label South Direction Label                  Georeference  
0             Last Stop             Manhattan  POINT (-73.912034 40.775036)  
1               Astoria             Manhattan  POINT (-73.917843 40.770258)  
2               Astoria             Manhattan  POINT (-73.921479 40.766779)  
3               Astoria             Manhattan   POINT (-73.925508 40.76182)  
4               Astoria             Manhattan  POINT (-73.929575 40.756804)

In [40]:
data = data[data['Borough'] != 'SI']
last_stops = data[data['North Direction Label'] == 'Last Stop']

last_stops.head()

GTFS Stop ID  Station ID  Complex ID Division                Line  \
0            R01           1           1      BMT             Astoria   
114          L01         115         618      BMT            Canarsie   
138          S01         139         627      BMT    Franklin Shuttle   
141          A02         143         143      IND  8th Av - Fulton St   
210          D01         210         210      IND           Concourse   

                Stop Name Borough Daytime Routes  GTFS Latitude  \
0    Astoria-Ditmars Blvd       Q            N W      40.775036   
114                  8 Av       M              L      40.739777   
138           Franklin Av      Bk              S      40.680596   
141         Inwood-207 St       M              A      40.868072   
210        Norwood-205 St      Bx              D      40.874811   

     GTFS Longitude North Direction Label South Direction Label  \
0        -73.912034             Last Stop             Manhattan   
114      -74.002578             Last Stop              Brooklyn   
138      -73.955827             Last Stop         Prospect Park   
141      -73.919899             Last Stop              Downtown   
210      -73.878855             Last Stop             Manhattan   

                     Georeference  
0    POINT (-73.912034 40.775036)  
114  POINT (-74.002578 40.739777)  
138  POINT (-73.955827 40.680596)  
141  POINT (-73.919899 40.868072)  
210  POINT (-73.878855 40.874811)

In [49]:
f_train = data[data['Daytime Routes'].str.contains('F')]

f_train

GTFS Stop ID  Station ID  Complex ID Division  \
56           D42          57          57      BMT   
57           D43          58          58      BMT   
167          D20         167         167      IND   
174          A41         174         636      IND   
221          B04         221         221      IND   
222          B06         222         222      IND   
223          B08         223         223      IND   
224          B10         224         224      IND   
225          D15         225         225      IND   
226          D16         226         609      IND   
227          D17         227         607      IND   
228          D18         228         228      IND   
229          D19         229         601      IND   
230          D21         230         619      IND   
232          F14         232         232      IND   
233          F15         233         625      IND   
234          F16         234         234      IND   
235          F18         235         235      IND   
236          F20         236         236      IND   
237          F21         237         237      IND   
238          F22         238         238      IND   
239          F23         239         608      IND   
240          F24         240         240      IND   
241          F25         241         241      IND   
242          F26         242         242      IND   
243          F27         243         243      IND   
244          F29         244         244      IND   
245          F30         245         245      IND   
246          F31         246         246      IND   
247          F32         247         247      IND   
248          F33         248         248      IND   
249          F34         249         249      IND   
250          F35         250         250      IND   
251          F36         251         251      IND   
252          F38         252         252      IND   
253          F39         253         253      IND   
254          F01         254         254      IND   
255          F02         255         255      IND   
256          F03         256         256      IND   
257          F04         257         257      IND   
258          F05         258         258      IND   
259          F06         259         259      IND   
260          F07         260         260      IND   
261          G08         261         261      IND   
267          G14         267         616      IND   

                                         Line                  Stop Name  \
56                        Broadway - Brighton         W 8 St-NY Aquarium   
57   Sea Beach / West End / Culver / Brighton  Coney Island-Stillwell Av   
167                           6th Av - Culver             W 4 St-Wash Sq   
174                        8th Av - Fulton St           Jay St-MetroTech   
221                                   63rd St         21 St-Queensbridge   
222                                   63rd St           Roosevelt Island   
223                                   63rd St         Lexington Av/63 St   
224                           6th Av - Culver                      57 St   
225                           6th Av - Culver  47-50 Sts-Rockefeller Ctr   
226                           6th Av - Culver            42 St-Bryant Pk   
227                           6th Av - Culver            34 St-Herald Sq   
228                           6th Av - Culver                      23 St   
229                           6th Av - Culver                      14 St   
230                           6th Av - Culver      Broadway-Lafayette St   
232                           6th Av - Culver                       2 Av   
233                           6th Av - Culver       Delancey St-Essex St   
234                           6th Av - Culver              East Broadway   
235                           6th Av - Culver                    York St   
236                           6th Av - Culver                  Bergen St   
237                           6th Av - Culver

Lets find a way to re order them to how the actual train line is.

In [52]:
def nearest_neighbor_path():
    return ""

def swap_rows(df, idx1, idx2):
    """Swap two rows in a DataFrame"""
    df.iloc[idx1], df.iloc[idx2] = df.iloc[idx2].copy(), df.iloc[idx1].copy()
    return df

swap_rows(f_train, 0, 1)

coords = f_train[['GTFS Latitude', 'GTFS Longitude']].values
distances = pdist(coords)
distance_matrix = squareform(distances)

#print(coords)
#print(distances)
print(distance_matrix)

[[0.         0.00545009 0.15610891 ... 0.20140791 0.19875542 0.19161732]
 [0.00545009 0.         0.15812929 ... 0.19858524 0.19611111 0.19035067]
 [0.15610891 0.15812929 0.         ... 0.16377109 0.15633697 0.11009047]
 ...
 [0.20140791 0.19858524 0.16377109 ... 0.         0.0079427  0.06098474]
 [0.19875542 0.19611111 0.15633697 ... 0.0079427  0.         0.05305171]
 [0.19161732 0.19035067 0.11009047 ... 0.06098474 0.05305171 0.        ]]
